---
# create-vm default vars

vm_name: microshift-dev
vm_disk_dir: /var/lib/libvirt/images
iso_file: /var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso
num_cpu: 4
ram_size: 6
disk_size: 50
swap_size: 6
data_volume_size: 2
