name = "microshift"

description = ""
version = "0.0.1"
modules = []
groups = []

# MicroShift and dependencies

[[packages]]
name = "microshift"
version = "${MICROSHIFT_VERSION}"

[[packages]]
name = "microshift-greenboot"
version = "${MICROSHIFT_VERSION}"

[[packages]]
name = "microshift-networking"
version = "${SOURCE_VERSION}"

[[packages]]
name = "microshift-selinux"
version = "${SOURCE_VERSION}"

[[packages]]
name = "microshift-release-info"
version = "${MICROSHIFT_VERSION}"

[[packages]]
name = "openshift-clients"
version = "*"

# troubleshooting tools

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "iotop"
version = "*"

[[packages]]
name = "strace"
version = "*"

# customizations

[customizations]

[customizations.services]
enabled = ["crio", "microshift"]
